trigger:
- main

schedules:
- cron: "30 20 * * *"
  displayName: Daily build
  branches:
    include:
    - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation:
      "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm install express
  displayName: 'Install express'

- script: |
    npm test
  displayName: 'Run tests'
